# Generated by Django 4.2.30 on 2026-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dailysalesreport_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesprocessingchunk',
            name='end_order_id',
        ),
        migrations.RemoveField(
            model_name='salesprocessingchunk',
            name='start_order_id',
        ),
        migrations.AddField(
            model_name='salesprocessingchunk',
            name='order_ids',
            field=models.JSONField(default=list),
        ),
    ]
