# Generated by Django 4.2.30 on 2026-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_salesprocessingchunk_processed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesreport',
            name='pdf_generation_time',
            field=models.FloatField(default=0.0),
        ),
    ]
