# Generated by Django 4.2.30 on 2026-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_dailysalesreport_pdf_generation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesreport',
            name='total_execution_time',
            field=models.FloatField(default=0.0),
        ),
    ]
