# Generated by Django 4.2.30 on 2026-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_dailysalesreport_total_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
