# Generated by Django 4.2.30 on 2026-06-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_dailysalesreport_status'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX idx_cart_product ON cart_items(cart_id, product_id);",
            reverse_sql="DROP INDEX idx_cart_product ON cart_items;"
        )
    ]
