worker_processes auto;

events {
    worker_connections 16384;
}

http {
    access_log off;
    error_log stderr crit;
    upstream django_cluster {
        server 127.0.0.1:8001 weight=5 max_fails=0 max_conns=1000;
        server 127.0.0.1:8002 weight=5 max_fails=0 max_conns=1000 down;
        server 127.0.0.1:8003 weight=5 max_fails=0 max_conns=1000 down;
    }
    keepalive_timeout 15;
    keepalive_requests 100000;

    server {
        listen 8080;

        proxy_read_timeout 3600;
        proxy_connect_timeout 30;
        proxy_send_timeout 3600;

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }

        location / {

            proxy_pass http://django_cluster;
            
            proxy_next_upstream error timeout;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
